# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "kctf"
  config.vm.define "kctf"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "#{Dir.home}/workspace", "/workspace", type: "nfs", nfs_udp: false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider :libvirt do |libvirt|
    # https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/README.md
    libvirt.driver = "kvm"
    libvirt.cpus = 4
    libvirt.memory = 4096
    #libvirt.nested = true
    #libvirt.volume_cache = "none"
    #libvirt.random_hostname = true
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # install essential build tools
    apt-get update
    apt-get install -y build-essential docker.io containerd gcc jq net-tools xxd wget curl netcat git socat

    # download and install latest golang
    GO_VERSION=$(curl -s https://go.dev/VERSION?m=text)
    wget -q -P /tmp https://go.dev/dl/${GO_VERSION}.linux-amd64.tar.gz
    tar -C /usr/local -xzf /tmp/${GO_VERSION}.linux-amd64.tar.gz
    rm /tmp/${GO_VERSION}.linux-amd64.tar.gz

    # Enable user namespaces
    echo 'kernel.unprivileged_userns_clone=1' | sudo tee -a /etc/sysctl.d/00-local-userns.conf
    sudo service procps restart

    # add vagrant user to appropriate groups
    usermod -a -G docker,kvm vagrant

    # setup root home directory
    mkdir -p ~/go/bin ~/go/src
    echo "export GOPATH=\$HOME/go" >> ~/.bashrc
    echo "export PATH=\$PATH:\$HOME/go/bin:/usr/local/go/bin" >> ~/.bashrc
    git clone https://github.com/dobsonj/dotfiles.git /tmp/dotfiles
    cp /tmp/dotfiles/.vimrc ~/
    cp /tmp/dotfiles/.screenrc ~/

    # setup vagrant home directory
    su vagrant -c 'mkdir -p ~/go/bin ~/go/src'
    su vagrant -c 'echo "export GOPATH=\\$HOME/go" >> ~/.bashrc'
    su vagrant -c 'echo "export PATH=\\$PATH:\\$HOME/go/bin:/usr/local/go/bin" >> ~/.bashrc'
    su vagrant -c 'cp /tmp/dotfiles/.vimrc ~/'
    su vagrant -c 'cp /tmp/dotfiles/.screenrc ~/'
    su vagrant -c 'echo "umask a+rx" >> ~/.bashrc'

    # download kctf: https://google.github.io/kctf/local-testing.html
    su vagrant -c 'mkdir ctf-dir && cd ctf-dir && curl -sSL https://kctf.dev/sdk | tar xz'

    # cleanup
    rm -r /tmp/dotfiles
  SHELL
end
